### ISSUE TITLE
todo in demo section

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#133]
- [x] update provenance browser section
 - [x] add instructions on how to plot band structure from AiiDA output

On tutorial VM:
 - [x] empty `~/.aiida_run` folder
 - [x] after upgrading aiida-core, run `reentry scan`
 - [x] after upgrading aiidalab, run `reentry scan` + check that the `psycopg2` warning does not come back

**Comment by ramirezfranciscof** [comment]
A few comments from testing the new tutorial in the new VMs:

### Section 2.1

- There is no jsmol in the VMs?
- After loading the structure: wouldn't this be a good place to introduce verdi node info querying? (`verdi node show 172` => `verdi data structure show 172` or `verdi node attributes 172`) Checking something you just loaded seems like a natural thing to do.
- I think you never tell them to initialize the daemon before the verdi run (or maybe I missed it?).

### Section 2.2

- Saul goodman.

### Section 2.3 (tried it with your VM 52.211.9.216)

- When configuring the neighbour machine for ssh, I'm getting 'Error: Invalid value for "--key-filename": path must be absolute'. Did I miss anything here? I fixed it by changing the `key_filename` in `neighbor-config.yml` for '/home/max/aiida-tutorials-compute.pem'.

### Section 2.4

- Could not connect to materials cloud, but this is still not working right? Hence the comment in the "Browse your AiiDA datbase" section I suppose (btw: database typo).

**Comment by ltalirz** [comment]
> There is no jsmol in the VMs?

Ah yes - it's `jmol`

> After loading the structure: wouldn't this be a good place to introduce verdi node info querying? (verdi node show 172 => verdi data structure show 172 or verdi node attributes 172) 

Thanks, we should keep it short but I'll think about adding 1 or 2 commands.

> I think you never tell them to initialize the daemon before the verdi run (or maybe I missed it?).

It's running as a system service, so it should be running already (to check!).

**Comment by ramirezfranciscof** [comment]
> Thanks. I guess you mean `/home/max/.ssh/aiida-tutorials-compute.pem`

Oh, haha, you are right. I didn't read properly that the key was already in the VM so I copied the one in my local machine and just left it there in my home and used that, but you are right.

> Hm... at least the basic connection _should_ work (workflows won't display properly).
> Can you try closing all open ssh terminals; then connect again and run `verdi restapi`
> then click the link?

Mmm noup. I'm getting a red "Error while connecting to new REST endpoint! [Network Connection Error]" banner when clicking on the link from your tutorial. If I try using the link in the [old EPFL tutorial](https://aiida-tutorials.readthedocs.io/en/xiamen2019/pages/2019_MARVEL_Psik_MaX/sections/verdi_cmdline.html#the-provenance-browser) but won't work either. I think I didn't miss anything in the config this time (I even added the extra line at the end of the config that was not in the other tutorial). I could go look for Casper if maybe he can figure out if I'm missing anything.

**Comment by ltalirz** [comment]
So, if you followed the setup instructions, port 5000 of the VM should be tunneled to your laptop.

I.e. if you open your browser and put  http://127.0.0.1:5000/api/v3 , you should see the endpoint.
If this does not work, then either the REST API is not running in the VM or the port is not forwarded properly.

**Comment by ltalirz** [comment]
One more thing I should have mentioned: This currently works only in Firefox and Chrome (not: Safari)

**Comment by ramirezfranciscof** [comment]
Yeah, no, nevermind, I was messing up with the ssh connection again (I had the wrong IP set up in the config). Now its working properly!

**Comment by ltalirz** [comment]
Ok, thanks for your help!

**Comment by ramirezfranciscof** [comment]
Sure, just let me know when you have more stuff you want to test!

**Comment by ltalirz** [comment]
todo items fixed in build 4
