### ISSUE TITLE
Bugs in AiiDA that should be addressed before the 2020 tutorial (for the `basics` section)

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-tutorials#216]
- [x] aiidateam/aiida-core#4183 (`--color` for `verdi node repo ls`)
- [x] aiidateam/aiida-core#4184 (tab completion for `calcjob.res`)
- [x] aiidateam/aiida-core#4185 (error in the REST API)

**Comment by chrisjsewell** [comment]
all fixed in aiida v1.3.0
