### ISSUE TITLE
🧪 TEST: Checklist for basics section and main page

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-tutorials#248]
List of things to check for the basics section of the tutorial:

- [ ] Add a comment in the "AiiDA basics" section to mention that it is taken from the basic aiida tutorial (even if just for us to remember in the future)
- [ ] search for "this tutorial" in the section copied from the docs and replace with the appropriate section name
- [x] replace link to (missing) appendix for computer setup with a link to the aiida-core docs after aiidateam/aiida-core#4216 is merged
- [X] ~~try to find a place where to mention groups~~ - This has been moved into the "Working with data and querying section" by @chrisjsewell in #231.
- [ ] try to find a place where to show the MC provenance explorer
- [X] ~~Move Outputs subsection to "Running computations" hands on.~~ See #251 
- [ ] Consider addressing #218 on pausing in basics (or running computations) section.
- [ ] See if we can wrap text in table columns to make sure tables fit the page width.
- [x] Add hands-on section for install once this is merged:
https://github.com/aiidateam/aiida-core/pull/4216#pullrequestreview-443055002
