### ISSUE TITLE
Checklist for updating tutorial VM image

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#53]
There are still a few issues with the current image (build 2.1).

Still to do:
 - [x] incorporate fix for ipython_magics (done via ansible on the existing VMs for now)
 - [x] install python3-tkinter (done via ansible on the existing VMs for now)

**Comment by ltalirz** [comment]
For Version 2.6
 - [x] update aiidalab role with updated `start.sh` (+ potentially home app / widgets that work with aiida 1.0)
 - [x] check slurm scheduler

**Comment by ltalirz** [comment]
Done in build 2.6
